# Generated by Django 3.2.9 on 2021-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.TextField()),
                ('imageListSlide', models.TextField()),
                ('video', models.TextField()),
                ('screenTech', models.CharField(max_length=100)),
                ('pixelRadio', models.CharField(max_length=100)),
                ('screenSize', models.CharField(max_length=100)),
                ('brightness', models.CharField(max_length=100)),
                ('frontCamera', models.CharField(max_length=100)),
                ('rearCamera', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('chip', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('rom', models.CharField(max_length=100)),
                ('sdCard', models.CharField(max_length=100)),
            ],
        ),
    ]
