export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS';

export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID';
export const GET_PRODUCTS_BY_ID_SUCCESS = 'GET_PRODUCTS_BY_ID_SUCCESS';

export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const ASC_PRODUCTS = 'ASC_PRODUCTS';
export const DESC_PRODUCTS = 'DESC_PRODUCTS';

export const PAGINATION_PRODUCTS = 'PAGINATION_PRODUCTS';
