# Generated by Django 3.2.9 on 2021-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
