# Generated by Django 3.2.9 on 2021-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_carts_idcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='idCart',
            field=models.IntegerField(),
        ),
    ]
