# Generated by Django 3.2.9 on 2021-12-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
