# Generated by Django 3.2.9 on 2021-12-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
