# Generated by Django 3.2.9 on 2021-12-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraccount_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
